### ISSUE TITLE
"@ ERROR 09: Unable to contact Meraki cloud"  for deviceupdownstatus.py

### ISSUE THREAD

**Issue by biswajitban** [meraki/automation-scripts#21]
Hi 
Having problem with deviceupdownstatus.py script , when gave output few days Back.
 python3 deviceupdownstatus.py  -k 1234 -o "XXx XXX XX"
Give output as 
"@ ERROR 09: Unable to contact Meraki cloud"

Platform- Linux ubuntu 20.04.1 LTS
Python 3.8 

Can you please help sorting out 

TIA 
Biswajit

**Comment by mpapazog** [comment]
I found the issue. If you fetch the latest version of the script, it should be fixed.

The script is very old and used a technique that is not valid anymore. (The SNMP settings endpoint used to return the dashboard shard the organization was stored in and the script sent API requests to this FQDN instead of api.meraki.com for a tiny performance boost.)

Please note that this script is indeed very old. Back when it was coded, there was no endpoint to get device up/down statuses, so SNMP had to be used. This script is best regarded as a tech demo of how to use the Dashboard API and SNMP in the same piec of code. To get the up/down status of your devices, you are better off using this more modern endpoint instead: https://developer.cisco.com/meraki/api-v1/#!get-organization-devices-statuses

**Comment by zabrewer** [comment]
@biswajitban, I have a simple script that may work for you - it is filtered by MX but you could easily change it for other products:
https://github.com/zabrewer/Meraki_Scripts/blob/master/mxdown.py
