### ISSUE TITLE
Trying to run usagestats script, getting null values for networks

### ISSUE THREAD

**Issue by etauPal** [meraki/automation-scripts#4]
I am running the `usagestats.py` , but the upload/download data seems to be off. 

-Not all networks show up for the given organization,
-the upload and download values for the networks are all 0 (even though there is traffic in them)
-reports set to `last-week` and `last-month` give the same results

**Comment by mpapazog** [comment]
Hi!

Could you post here the exact commands you use to run the script, as well as the time range you expect to get data from? Please do mask sensitive information, like your API key.

**Comment by shwetapalande** [comment]
using the below command
` python usagestats.py -k xxxxxxxxxxxx -i usagestats.init report:last-week`

usagestats.init file has the following config
`[OPTIONS]
database=sample.db
filter=org:myorg name`

**Comment by mpapazog** [comment]
With those parameters, the expected behaviour of the script is the following:
* It will only pull information from networks that contain MX security appliances and Z-series teleworker gateways. To override this default behaviour, use the "dtype" filter.
* The "last-week" option runs a report for the last full Monday-Sunday week. It is not the same as running a report for the last 7 days.

With these notes in mind, do you still feel that the script is not working as expected?
